version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dphones
    ports:
      - 8090:8090
    restart: always
    image: duonga6/dphones
    
  nginx:
    build:
       context: .
       dockerfile: Dockerfile.nginx
    image: duonga6/nginx-dphones
    container_name: nginx-dphones
    ports:
      - 80:80
      - 443:443