version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dphones
    ports:
      - 8090:8090
    restart: always
    image: duonga6/dphones
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./ssl/certificate.pem:/etc/nginx/ssl/certificate.pem
      - ./ssl/private.pem:/etc/nginx/ssl/private.pem