FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf

COPY proxy.conf /etc/nginx/proxy.conf

COPY ssl/certificate.pem /etc/nginx/ssl/certificate.pem

COPY ssl/private.pem /etc/nginx/ssl/private.pem