version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - deployment_network
    ports:
      - 8090:8090
    restart: always
    volumes:
      - dphones-backup-volume:/app/BackupDB
volumes:
  dphones-backup-volume:
    external: true
networks:
  deployment_network:
    external: true