name: CICD-Docker

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with compose
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Add tag
        run: |
          docker tag nginx duonga6/nginx-dphones

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dphones
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-dphones

      - name: Test container
        run: |
          docker ps -a
          
  update_server:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker image pull duonga6/dphones
            docker image pull duonga6/nginx-dphones
            docker container stop dphones
            docker container stop nginx-dphones
            docker container prune -f
            docker run -d --network nginx-dphones --name dphones --restart unless-stopped -p 8089:8090 duonga6/dphones
            docker run -d --network nginx-dphones --name nginx-dphones -p 80:80 -p 443:443 duonga6/nginx-dphones
            docker image prune -f
